/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as GoalGoalIdRouteImport } from './routes/goal.$goalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalGoalIdRoute = GoalGoalIdRouteImport.update({
  id: '/goal/$goalId',
  path: '/goal/$goalId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/progress': typeof ProgressRoute
  '/goal/$goalId': typeof GoalGoalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/progress': typeof ProgressRoute
  '/goal/$goalId': typeof GoalGoalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/progress': typeof ProgressRoute
  '/goal/$goalId': typeof GoalGoalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/overview' | '/progress' | '/goal/$goalId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/overview' | '/progress' | '/goal/$goalId'
  id: '__root__' | '/' | '/overview' | '/progress' | '/goal/$goalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OverviewRoute: typeof OverviewRoute
  ProgressRoute: typeof ProgressRoute
  GoalGoalIdRoute: typeof GoalGoalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goal/$goalId': {
      id: '/goal/$goalId'
      path: '/goal/$goalId'
      fullPath: '/goal/$goalId'
      preLoaderRoute: typeof GoalGoalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OverviewRoute: OverviewRoute,
  ProgressRoute: ProgressRoute,
  GoalGoalIdRoute: GoalGoalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
